name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      GRADLE_OPTS: -Xmx1280m
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windowns-latest]
        java: [11]
        include:
          - java: 11
            os: ubuntu-latest
            coverage: true
          - java: 8
            os: ubuntu-latest
          - java: 14
            os: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}

    - name: Build with Gradle
      uses: burrunan/gradle-cache-action@v1.10
      with:
        remote-build-cache-proxy-enabled: false
        arguments: --no-daemon --stacktrace checkstyle check build ${{ matrix.coverage && '-Pcoverage' || '' }}

    - name: Codecov Report
    - if: ${{ matrix.coverage }}
      uses: codecov/codecov-action@v1

    - name: Collecting the test reports ..
      if: failure()
      run: find . '(' -name 'hs_err_*.log' -or -path '*/build/reports/tests' ')' -exec tar rf "reports-JVM-${{ matrix.java }}.tar" {} ';'

    - name: Upload Artifact
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: reports-JVM-${{ matrix.java }}
        path: reports-JVM-${{ matrix.java }}.tar
        retention-days: 3
